app/src/Entity/Report.php
<?php

namespace App\Entity;

use App\Repository\ReportRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReportRepository::class)
 */
class Report
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $export_name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $export_time;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $user_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $place_name;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getExportName(): ?string
    {
        return $this->export_name;
    }

    public function setExportName(string $export_name): self
    {
        $this->export_name = $export_name;

        return $this;
    }

    public function getExportTime(): ?\DateTimeInterface
    {
        return $this->export_time;
    }

    public function setExportTime(\DateTimeInterface $export_time): self
    {
        $this->export_time = $export_time;

        return $this;
    }

    public function getUserName(): ?string
    {
        return $this->user_name;
    }

    public function setUserName(string $user_name): self
    {
        $this->user_name = $user_name;

        return $this;
    }

    public function getPlaceName(): ?string
    {
        return $this->place_name;
    }

    public function setPlaceName(?string $place_name): self
    {
        $this->place_name = $place_name;

        return $this;
    }
}

app/src/Controller/ReportController.php
<?php

namespace App\Controller;

use App\Entity\Report;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;


class ReportController extends AbstractController
{
    /**
     * @Route("/report", name="report")
     */
    public function index(Request $request): Response
    {
        $reportRepository = $this->getDoctrine()->getRepository('App:Report');
        $allReports = $reportRepository->findAll();

        $form = $this->createFormBuilder()
            ->add('place_name', TextType::class, ['label' => 'Lokal'])
            ->add('export_time', DateType::class, ['label' => 'data'])
            ->add('save', SubmitType::class, ['label' => 'Zatwierdź'])
            ->getForm();


        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $filteredReports = $reportRepository->findBy(array('place_name' => $form->get('place_name')->getViewData()));

            return $this->render('report/index.html.twig', array(
                'report_data' => $filteredReports,
                'form' => $form->createView()
            ));
        }


        return $this->render('report/index.html.twig', [
            'controller_name' => 'ReportController',
            'report_data' => $allReports,
            'form' => $form->createView()
        ]);
    }
}

app/templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            {#{{ encore_entry_link_tags('app') }}#}
        {% endblock %}

        {% block javascripts %}
            {#{{ encore_entry_script_tags('app') }}#}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

app/templates/report/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ReportController!{% endblock %}

{% block body %}
<style>
    table, th, td {
        border: 1px solid black;
    }
</style>

<div class="example-wrapper" style="display:flex">
    <div>
        {{ form(form) }}
    </div>
    <table class="tg">
        <thead>
        <tr>
            <th class="tg-0pky">Nazwa</th>
            <th class="tg-0pky">Data</th>
            <th class="tg-0pky">Godzina</th>
            <th class="tg-0pky">Użytkownik</th>
            <th class="tg-0pky">Lokal</th>
        </tr>
        </thead>
        <tbody>
        {% for report in report_data %}
        <tr>
            <td class="tg-0pky">{{ report.exportName }}</td>
            <td class="tg-0pky">{{ report.exportTime|date('d-m-Y') }}</td>
            <td class="tg-0pky">{{ report.exportTime|date('H:i:s') }}</td>
            <td class="tg-0pky">{{ report.userName }}</td>
            <td class="tg-0pky">{{ report.placeName }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}